import { Hotel } from './types/hotel';
import { ApartmentType } from './enums/apartment-type';
import { Goods } from './enums/good';

export const hotels: Hotel[] = [
  {
    id: '1',
    name: 'Amsterdam hotel',
    title: 'Amsterdam best hotel',
    type: ApartmentType.Apartment,
    description: 'Amsterdam hotel',
    city: { name: 'Amsterdam', location: { latitude: 1, longitude: 1.1, zoom: 1 } },
    bedrooms: 2,
    goods: [Goods.CableTV],
    host: { id: 'host_1', name: 'host 1', avatarUrl: '', isPro: true },
    previewImage: 'img/apartment-01.jpg',
    images: [],
    isFavorite: false,
    isPremium: false,
    location: { latitude: 1.2, longitude: 1.1, zoom: 2 },
    maxAdults: 4,
    price: 120,
    ratting: 4.5,
  },
  {
    id: '2',
    name: 'Amsterdam hotel',
    title: 'Amsterdam best hotel',
    type: ApartmentType.Apartment,
    description: 'Amsterdam hotel',
    city: { name: 'Amsterdam', location: { latitude: 1, longitude: 1.1, zoom: 1 } },
    bedrooms: 2,
    goods: [Goods.CableTV],
    host: { id: 'host_1', name: 'host 1', avatarUrl: '', isPro: true },
    previewImage: 'img/apartment-02.jpg',
    images: [],
    isFavorite: false,
    isPremium: false,
    location: { latitude: 1.2, longitude: 1.1, zoom: 2 },
    maxAdults: 4,
    price: 120,
    ratting: 4.5,
  },
  {
    id: '3',
    name: 'Amsterdam hotel',
    title: 'Amsterdam best hotel',
    type: ApartmentType.Apartment,
    description: 'Amsterdam hotel',
    city: { name: 'Amsterdam', location: { latitude: 1, longitude: 1.1, zoom: 1 } },
    bedrooms: 2,
    goods: [Goods.CableTV],
    host: { id: 'host_1', name: 'host 1', avatarUrl: '', isPro: true },
    previewImage: 'img/apartment-03.jpg',
    images: [],
    isFavorite: false,
    isPremium: true,
    location: { latitude: 1.2, longitude: 1.1, zoom: 2 },
    maxAdults: 4,
    price: 120,
    ratting: 4.5,
  },
  {
    id: '4',
    name: 'Amsterdam hotel',
    title: 'Amsterdam best hotel',
    type: ApartmentType.Apartment,
    description: 'Amsterdam hotel',
    city: { name: 'Amsterdam', location: { latitude: 1, longitude: 1.1, zoom: 1 } },
    bedrooms: 2,
    goods: [Goods.CableTV],
    host: { id: 'host_1', name: 'host 1', avatarUrl: '', isPro: true },
    previewImage: 'img/apartment-01.jpg',
    images: [],
    isFavorite: true,
    isPremium: false,
    location: { latitude: 1.2, longitude: 1.1, zoom: 2 },
    maxAdults: 4,
    price: 120,
    ratting: 4.5,
  },
  {
    id: '5',
    name: 'Amsterdam hotel',
    title: 'Amsterdam best hotel',
    type: ApartmentType.Apartment,
    description: 'Amsterdam hotel',
    city: { name: 'Amsterdam', location: { latitude: 1, longitude: 1.1, zoom: 1 } },
    bedrooms: 2,
    goods: [Goods.CableTV],
    host: { id: 'host_1', name: 'host 1', avatarUrl: '', isPro: true },
    previewImage: 'img/apartment-02.jpg',
    images: [],
    isFavorite: true,
    isPremium: true,
    location: { latitude: 1.2, longitude: 1.1, zoom: 2 },
    maxAdults: 4,
    price: 120,
    ratting: 4.5,
  },
];
